### ISSUE TITLE
RadioFinderD.py  stürzt ab

### ISSUE THREAD

**Issue by jolinux** [Axel-Erfurt/InternetRadioDeutsch#2]
Verwende die hochgeladene Datei 

myRadioD.tar.gz  

und habe Probleme mit dem Tool RadioFinderD.py

In der Konsole gibt es folgende Fehlermeldung:

Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
Traceback (most recent call last):
  File "RadioFinderD.py", line 370, in comboSearch
    self.findStations()
  File "RadioFinderD.py", line 498, in findStations
    r = rb.station_search(params=myparams)
  File "RadioFinderD.py", line 243, in station_search
    return request(endpoint, **kwargs)
  File "RadioFinderD.py", line 64, in request
    return resp.json()
  File "requests/models.py", line 897, in json
  File "simplejson/__init__.py", line 525, in loads
  File "simplejson/decoder.py", line 370, in decode
  File "simplejson/decoder.py", line 400, in raw_decode
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Abgebrochen

Gestartet als ./myRadioD

und im Menü dann den Radiofinder aufgerufen.

Identisch ist der Fehler bei Einzelaufruf ./RadioFinderD

Auch bei der 64er-Version als tar-File ist der Fehler vorhanden.

System DEbian Buster mit Python3.7

Danke für deine Unterstützung und die schon  erbrachte Leistung für das Tool

Jörg

**Comment by Axel-Erfurt** [comment]
Ich habe LMDE5 (Debian Bullseye)

Diese alte Version bringt dort die gleichen Fehler.

Die neuere Version von Releases funktioniert, dort ist die Suche im Hauptfenster integriert.

https://github.com/Axel-Erfurt/InternetRadioDeutsch/releases/download/v1.0/myRadioD.tar.gz

**Radio-Suche anzeigen** klicken.

![radiotest1](https://user-images.githubusercontent.com/2623542/191794651-772ce2bb-ec89-4bd9-a9da-ae99a824d394.png)
![radiotest](https://user-images.githubusercontent.com/2623542/191794682-ebd4787a-d665-4cc8-8f2f-dd3ee515a2ea.png)

**Comment by jolinux** [comment]
Leider ist diese Version scheinbar gegen  `GLIBC_2.29' gelinkt und somit erst ab Debian 11 nutzbar. Schade !

Debian 10 Buster meldet 

o@buster:~/Downloads/myRadioD$ ldd --version
ldd (Debian GLIBC 2.28-10+deb10u1) 2.28


jo@buster:~/Downloads/myRadioD$ ./myRadioD 
[13916] Error loading Python lib '/home/jo/Downloads/myRadioD/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/jo/Downloads/myRadioD/libpython3.8.so.1.0)

**Comment by Axel-Erfurt** [comment]
Die Anleitung auf [myRadio UbuntuUsers Wiki ](https://wiki.ubuntuusers.de/Howto/myRadio/) funktioniert auch auf Debian 10.

Habe es mit Debian 10 xfce getestet.
